### ISSUE TITLE
Handling QA/Gas issues upgraded to Medium/High

### ISSUE THREAD

**Issue by CloudEllie** [code-423n4/rulebook#10]
**Context:** Since instating the mechanism change around QA and Gas reports, it's become apparent that there's an open question about how to handle changes in severity, when they cross over from QA/Gas to Medium/High, or vice versa.

## Handling QA/Gas issues upgraded to Medium/High

These are simpler than downgraded Med/High submissions in a sense, because the awarding mechanism is straightforward. However, it raises a question for me in that maybe if a warden can't figure out why or how a vuln could become medium/high risk, they haven't earned a Medium/High payout? This one just feels nuanced, so I would love to hear from judges as well as wardens. 

Relatedly: at the moment, this scenario requires significant additional effort from judges and contest admins, because we've asked them to copy/paste the relevant issue from the QA/Gas report into a new issue in Github, then add it to the findings sheet, and there's extra effort required to ensure that our tooling "catches" the new issues for award calculation (because the issues were not submitted via the submission form and attached to the warden's handle). 

Obviously we'll be improving our tooling to handle these needs, but I think there's also a need to establish consensus around what's fair and appropriate.

(See also issue #9 , which is related.)

**Comment by MrToph** [comment]
Seems to be mostly a tooling limitation? (and I agree it's a rather big one.)
But once the issues are correctly upgraded from QA report, or downgraded into a QA report, the standard rules can apply.

>  if a warden can't figure out why or how a vuln could become medium/high risk, they haven't earned a Medium/High payout? 

Agree, I imagine upgrades to be quite rare.

**Comment by CloudEllie** [comment]
Closing this as it seems we have sufficient consensus to move forward. Current approach is documented in the C4 docs: https://docs.code4rena.com/roles/judges/how-to-judge-a-contest#upgrading-issues-from-qa-gas-to-medium-high
