### ISSUE TITLE
Handling High/Med risk issues downgraded to Low/Non-crit/Gas

### ISSUE THREAD

**Issue by CloudEllie** [code-423n4/rulebook#9]
Since instating the mechanism change around QA and Gas reports, it's become apparent that there's an open question about how to handle changes in severity, when they cross over from QA/Gas to Medium/High, or vice versa. 

I'm going to file these as separate issues (starting with the one I think is trickier), so we can keep discussion focused.

## High/Med risk issue downgraded to Low/Non-crit/Gas

Should we handle these as: 

1. stand-alone QA/gas reports, that need to be scored on the 0-100 scale?
2. addenda to a warden's existing QA/gas report (if one was submitted)? (Perhaps if the warden has not submitted QA/Gas report, the judge would score it as a stand-alone, so would likely receive a low score.)
3. invalid issues, since they were submitted at the wrong risk level? (Pretty harsh, IMO.)
4. old-style Low/Non-crit findings? (I think this one is likely a non-starter as it would seriously muddy the waters as far as incentive structure, and make award calculation unnecessarily complex.)

**Comment by MrToph** [comment]
I'd say 2)

**Comment by CloudEllie** [comment]
We are proceeding with the approach described in (2) in my original post, at least for now. 

If the warden has not submitted a QA/Gas report, the judge will score the downgraded issue as a single-issue QA report -- or if the warden has multiple downgraded issues, they will receive a grouped QA score.

**Comment by CloudEllie** [comment]
Closing this issue as we seem to have sufficient consensus. Current approach is outlined in our judging docs: https://docs.code4rena.com/roles/judges/how-to-judge-a-contest#downgrading-issues-from-medium-high-to-qa-gas
